language: julia
os:
  - linux
  - osx
julia:
  - 0.7
  - 1.0
  - nightly

notifications:
  email: false

#script: # the default script is equivalent to the following
#  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#  - julia -e 'Pkg.clone(pwd()); Pkg.build("Digits"); Pkg.test("Digits"; coverage=true)';

after_success:
  - julia -e 'if VERSION >= v"0.7.0-" using Pkg end; cd(Pkg.dir("Digits")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())';
#  - julia -e 'if VERSION >= v"0.7.0-" using Pkg end; cd(Pkg.dir("Digits")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())';
